package com.example.schooljournal.services;

import static org.junit.jupiter.api.Assertions.assertSame;
import static org.mockito.Mockito.atLeast;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.example.schooljournal.data.entity.core.Address;
import com.example.schooljournal.data.entity.user.User;
import com.example.schooljournal.data.entity.user.enums.SchoolRole;
import com.example.schooljournal.data.repository.UserRepository;

import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.Date;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ContextConfiguration(classes = {UserService.class})
@ExtendWith(SpringExtension.class)
class UserServiceTest {
    @MockBean
    private UserRepository userRepository;

    @Autowired
    private UserService userService;

    /**
     * Method under test: {@link UserService#loadUserByUsername(String)}
     */
    @Test
    void testLoadUserByUsername() throws UsernameNotFoundException {
        // Arrange
        User creator = new User();
        creator.setAddress(new Address());
        creator.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator.setCreator(new User());
        creator.setDeleted(true);
        creator.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator.setEditor(new User());
        creator.setEmail("jane.doe@example.org");
        creator.setFirstName("Jane");
        creator.setId(1L);
        creator.setLastName("Doe");
        creator.setPassword("iloveyou");
        creator.setSchoolRole(SchoolRole.TEACHER);

        User editor = new User();
        editor.setAddress(new Address());
        editor.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor.setCreator(new User());
        editor.setDeleted(true);
        editor.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor.setEditor(new User());
        editor.setEmail("jane.doe@example.org");
        editor.setFirstName("Jane");
        editor.setId(1L);
        editor.setLastName("Doe");
        editor.setPassword("iloveyou");
        editor.setSchoolRole(SchoolRole.TEACHER);

        Address address = new Address();
        address.setCity("Oxford");
        address.setCountryCode("GB");
        address.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address.setCreator(creator);
        address.setDeleted(true);
        address.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address.setEditor(editor);
        address.setHouseNumber("42");
        address.setId(1L);
        address.setStreet("Street");

        Address address2 = new Address();
        address2.setCity("Oxford");
        address2.setCountryCode("GB");
        address2.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address2.setCreator(new User());
        address2.setDeleted(true);
        address2.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address2.setEditor(new User());
        address2.setHouseNumber("42");
        address2.setId(1L);
        address2.setStreet("Street");

        User creator2 = new User();
        creator2.setAddress(new Address());
        creator2.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator2.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator2.setCreator(new User());
        creator2.setDeleted(true);
        creator2.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator2.setEditor(new User());
        creator2.setEmail("jane.doe@example.org");
        creator2.setFirstName("Jane");
        creator2.setId(1L);
        creator2.setLastName("Doe");
        creator2.setPassword("iloveyou");
        creator2.setSchoolRole(SchoolRole.TEACHER);

        User editor2 = new User();
        editor2.setAddress(new Address());
        editor2.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor2.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor2.setCreator(new User());
        editor2.setDeleted(true);
        editor2.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor2.setEditor(new User());
        editor2.setEmail("jane.doe@example.org");
        editor2.setFirstName("Jane");
        editor2.setId(1L);
        editor2.setLastName("Doe");
        editor2.setPassword("iloveyou");
        editor2.setSchoolRole(SchoolRole.TEACHER);

        User creator3 = new User();
        creator3.setAddress(address2);
        creator3.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator3.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator3.setCreator(creator2);
        creator3.setDeleted(true);
        creator3.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator3.setEditor(editor2);
        creator3.setEmail("jane.doe@example.org");
        creator3.setFirstName("Jane");
        creator3.setId(1L);
        creator3.setLastName("Doe");
        creator3.setPassword("iloveyou");
        creator3.setSchoolRole(SchoolRole.TEACHER);

        Address address3 = new Address();
        address3.setCity("Oxford");
        address3.setCountryCode("GB");
        address3.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address3.setCreator(new User());
        address3.setDeleted(true);
        address3.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address3.setEditor(new User());
        address3.setHouseNumber("42");
        address3.setId(1L);
        address3.setStreet("Street");

        User creator4 = new User();
        creator4.setAddress(new Address());
        creator4.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator4.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator4.setCreator(new User());
        creator4.setDeleted(true);
        creator4.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator4.setEditor(new User());
        creator4.setEmail("jane.doe@example.org");
        creator4.setFirstName("Jane");
        creator4.setId(1L);
        creator4.setLastName("Doe");
        creator4.setPassword("iloveyou");
        creator4.setSchoolRole(SchoolRole.TEACHER);

        User editor3 = new User();
        editor3.setAddress(new Address());
        editor3.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor3.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor3.setCreator(new User());
        editor3.setDeleted(true);
        editor3.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor3.setEditor(new User());
        editor3.setEmail("jane.doe@example.org");
        editor3.setFirstName("Jane");
        editor3.setId(1L);
        editor3.setLastName("Doe");
        editor3.setPassword("iloveyou");
        editor3.setSchoolRole(SchoolRole.TEACHER);

        User editor4 = new User();
        editor4.setAddress(address3);
        editor4.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor4.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor4.setCreator(creator4);
        editor4.setDeleted(true);
        editor4.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor4.setEditor(editor3);
        editor4.setEmail("jane.doe@example.org");
        editor4.setFirstName("Jane");
        editor4.setId(1L);
        editor4.setLastName("Doe");
        editor4.setPassword("iloveyou");
        editor4.setSchoolRole(SchoolRole.TEACHER);

        User creator5 = new User();
        creator5.setAddress(address);
        creator5.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator5.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator5.setCreator(creator3);
        creator5.setDeleted(true);
        creator5.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator5.setEditor(editor4);
        creator5.setEmail("jane.doe@example.org");
        creator5.setFirstName("Jane");
        creator5.setId(1L);
        creator5.setLastName("Doe");
        creator5.setPassword("iloveyou");
        creator5.setSchoolRole(SchoolRole.TEACHER);

        User creator6 = new User();
        creator6.setAddress(new Address());
        creator6.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator6.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator6.setCreator(new User());
        creator6.setDeleted(true);
        creator6.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator6.setEditor(new User());
        creator6.setEmail("jane.doe@example.org");
        creator6.setFirstName("Jane");
        creator6.setId(1L);
        creator6.setLastName("Doe");
        creator6.setPassword("iloveyou");
        creator6.setSchoolRole(SchoolRole.TEACHER);

        User editor5 = new User();
        editor5.setAddress(new Address());
        editor5.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor5.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor5.setCreator(new User());
        editor5.setDeleted(true);
        editor5.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor5.setEditor(new User());
        editor5.setEmail("jane.doe@example.org");
        editor5.setFirstName("Jane");
        editor5.setId(1L);
        editor5.setLastName("Doe");
        editor5.setPassword("iloveyou");
        editor5.setSchoolRole(SchoolRole.TEACHER);

        Address address4 = new Address();
        address4.setCity("Oxford");
        address4.setCountryCode("GB");
        address4.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address4.setCreator(creator6);
        address4.setDeleted(true);
        address4.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address4.setEditor(editor5);
        address4.setHouseNumber("42");
        address4.setId(1L);
        address4.setStreet("Street");

        Address address5 = new Address();
        address5.setCity("Oxford");
        address5.setCountryCode("GB");
        address5.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address5.setCreator(new User());
        address5.setDeleted(true);
        address5.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address5.setEditor(new User());
        address5.setHouseNumber("42");
        address5.setId(1L);
        address5.setStreet("Street");

        User creator7 = new User();
        creator7.setAddress(new Address());
        creator7.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator7.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator7.setCreator(new User());
        creator7.setDeleted(true);
        creator7.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator7.setEditor(new User());
        creator7.setEmail("jane.doe@example.org");
        creator7.setFirstName("Jane");
        creator7.setId(1L);
        creator7.setLastName("Doe");
        creator7.setPassword("iloveyou");
        creator7.setSchoolRole(SchoolRole.TEACHER);

        User editor6 = new User();
        editor6.setAddress(new Address());
        editor6.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor6.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor6.setCreator(new User());
        editor6.setDeleted(true);
        editor6.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor6.setEditor(new User());
        editor6.setEmail("jane.doe@example.org");
        editor6.setFirstName("Jane");
        editor6.setId(1L);
        editor6.setLastName("Doe");
        editor6.setPassword("iloveyou");
        editor6.setSchoolRole(SchoolRole.TEACHER);

        User creator8 = new User();
        creator8.setAddress(address5);
        creator8.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator8.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator8.setCreator(creator7);
        creator8.setDeleted(true);
        creator8.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator8.setEditor(editor6);
        creator8.setEmail("jane.doe@example.org");
        creator8.setFirstName("Jane");
        creator8.setId(1L);
        creator8.setLastName("Doe");
        creator8.setPassword("iloveyou");
        creator8.setSchoolRole(SchoolRole.TEACHER);

        Address address6 = new Address();
        address6.setCity("Oxford");
        address6.setCountryCode("GB");
        address6.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address6.setCreator(new User());
        address6.setDeleted(true);
        address6.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address6.setEditor(new User());
        address6.setHouseNumber("42");
        address6.setId(1L);
        address6.setStreet("Street");

        User creator9 = new User();
        creator9.setAddress(new Address());
        creator9.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator9.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator9.setCreator(new User());
        creator9.setDeleted(true);
        creator9.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator9.setEditor(new User());
        creator9.setEmail("jane.doe@example.org");
        creator9.setFirstName("Jane");
        creator9.setId(1L);
        creator9.setLastName("Doe");
        creator9.setPassword("iloveyou");
        creator9.setSchoolRole(SchoolRole.TEACHER);

        User editor7 = new User();
        editor7.setAddress(new Address());
        editor7.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor7.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor7.setCreator(new User());
        editor7.setDeleted(true);
        editor7.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor7.setEditor(new User());
        editor7.setEmail("jane.doe@example.org");
        editor7.setFirstName("Jane");
        editor7.setId(1L);
        editor7.setLastName("Doe");
        editor7.setPassword("iloveyou");
        editor7.setSchoolRole(SchoolRole.TEACHER);

        User editor8 = new User();
        editor8.setAddress(address6);
        editor8.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor8.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor8.setCreator(creator9);
        editor8.setDeleted(true);
        editor8.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor8.setEditor(editor7);
        editor8.setEmail("jane.doe@example.org");
        editor8.setFirstName("Jane");
        editor8.setId(1L);
        editor8.setLastName("Doe");
        editor8.setPassword("iloveyou");
        editor8.setSchoolRole(SchoolRole.TEACHER);

        User editor9 = new User();
        editor9.setAddress(address4);
        editor9.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor9.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor9.setCreator(creator8);
        editor9.setDeleted(true);
        editor9.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor9.setEditor(editor8);
        editor9.setEmail("jane.doe@example.org");
        editor9.setFirstName("Jane");
        editor9.setId(1L);
        editor9.setLastName("Doe");
        editor9.setPassword("iloveyou");
        editor9.setSchoolRole(SchoolRole.TEACHER);

        Address address7 = new Address();
        address7.setCity("Oxford");
        address7.setCountryCode("GB");
        address7.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address7.setCreator(creator5);
        address7.setDeleted(true);
        address7.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address7.setEditor(editor9);
        address7.setHouseNumber("42");
        address7.setId(1L);
        address7.setStreet("Street");

        Address address8 = new Address();
        address8.setCity("Oxford");
        address8.setCountryCode("GB");
        address8.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address8.setCreator(new User());
        address8.setDeleted(true);
        address8.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address8.setEditor(new User());
        address8.setHouseNumber("42");
        address8.setId(1L);
        address8.setStreet("Street");

        User creator10 = new User();
        creator10.setAddress(new Address());
        creator10.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator10.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator10.setCreator(new User());
        creator10.setDeleted(true);
        creator10.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator10.setEditor(new User());
        creator10.setEmail("jane.doe@example.org");
        creator10.setFirstName("Jane");
        creator10.setId(1L);
        creator10.setLastName("Doe");
        creator10.setPassword("iloveyou");
        creator10.setSchoolRole(SchoolRole.TEACHER);

        User editor10 = new User();
        editor10.setAddress(new Address());
        editor10.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor10.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor10.setCreator(new User());
        editor10.setDeleted(true);
        editor10.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor10.setEditor(new User());
        editor10.setEmail("jane.doe@example.org");
        editor10.setFirstName("Jane");
        editor10.setId(1L);
        editor10.setLastName("Doe");
        editor10.setPassword("iloveyou");
        editor10.setSchoolRole(SchoolRole.TEACHER);

        User creator11 = new User();
        creator11.setAddress(address8);
        creator11.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator11.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator11.setCreator(creator10);
        creator11.setDeleted(true);
        creator11.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator11.setEditor(editor10);
        creator11.setEmail("jane.doe@example.org");
        creator11.setFirstName("Jane");
        creator11.setId(1L);
        creator11.setLastName("Doe");
        creator11.setPassword("iloveyou");
        creator11.setSchoolRole(SchoolRole.TEACHER);

        Address address9 = new Address();
        address9.setCity("Oxford");
        address9.setCountryCode("GB");
        address9.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address9.setCreator(new User());
        address9.setDeleted(true);
        address9.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address9.setEditor(new User());
        address9.setHouseNumber("42");
        address9.setId(1L);
        address9.setStreet("Street");

        User creator12 = new User();
        creator12.setAddress(new Address());
        creator12.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator12.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator12.setCreator(new User());
        creator12.setDeleted(true);
        creator12.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator12.setEditor(new User());
        creator12.setEmail("jane.doe@example.org");
        creator12.setFirstName("Jane");
        creator12.setId(1L);
        creator12.setLastName("Doe");
        creator12.setPassword("iloveyou");
        creator12.setSchoolRole(SchoolRole.TEACHER);

        User editor11 = new User();
        editor11.setAddress(new Address());
        editor11.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor11.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor11.setCreator(new User());
        editor11.setDeleted(true);
        editor11.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor11.setEditor(new User());
        editor11.setEmail("jane.doe@example.org");
        editor11.setFirstName("Jane");
        editor11.setId(1L);
        editor11.setLastName("Doe");
        editor11.setPassword("iloveyou");
        editor11.setSchoolRole(SchoolRole.TEACHER);

        User editor12 = new User();
        editor12.setAddress(address9);
        editor12.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor12.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor12.setCreator(creator12);
        editor12.setDeleted(true);
        editor12.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor12.setEditor(editor11);
        editor12.setEmail("jane.doe@example.org");
        editor12.setFirstName("Jane");
        editor12.setId(1L);
        editor12.setLastName("Doe");
        editor12.setPassword("iloveyou");
        editor12.setSchoolRole(SchoolRole.TEACHER);

        Address address10 = new Address();
        address10.setCity("Oxford");
        address10.setCountryCode("GB");
        address10.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address10.setCreator(creator11);
        address10.setDeleted(true);
        address10.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address10.setEditor(editor12);
        address10.setHouseNumber("42");
        address10.setId(1L);
        address10.setStreet("Street");

        User creator13 = new User();
        creator13.setAddress(new Address());
        creator13.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator13.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator13.setCreator(new User());
        creator13.setDeleted(true);
        creator13.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator13.setEditor(new User());
        creator13.setEmail("jane.doe@example.org");
        creator13.setFirstName("Jane");
        creator13.setId(1L);
        creator13.setLastName("Doe");
        creator13.setPassword("iloveyou");
        creator13.setSchoolRole(SchoolRole.TEACHER);

        User editor13 = new User();
        editor13.setAddress(new Address());
        editor13.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor13.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor13.setCreator(new User());
        editor13.setDeleted(true);
        editor13.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor13.setEditor(new User());
        editor13.setEmail("jane.doe@example.org");
        editor13.setFirstName("Jane");
        editor13.setId(1L);
        editor13.setLastName("Doe");
        editor13.setPassword("iloveyou");
        editor13.setSchoolRole(SchoolRole.TEACHER);

        Address address11 = new Address();
        address11.setCity("Oxford");
        address11.setCountryCode("GB");
        address11.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address11.setCreator(creator13);
        address11.setDeleted(true);
        address11.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address11.setEditor(editor13);
        address11.setHouseNumber("42");
        address11.setId(1L);
        address11.setStreet("Street");

        Address address12 = new Address();
        address12.setCity("Oxford");
        address12.setCountryCode("GB");
        address12.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address12.setCreator(new User());
        address12.setDeleted(true);
        address12.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address12.setEditor(new User());
        address12.setHouseNumber("42");
        address12.setId(1L);
        address12.setStreet("Street");

        User creator14 = new User();
        creator14.setAddress(new Address());
        creator14.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator14.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator14.setCreator(new User());
        creator14.setDeleted(true);
        creator14.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator14.setEditor(new User());
        creator14.setEmail("jane.doe@example.org");
        creator14.setFirstName("Jane");
        creator14.setId(1L);
        creator14.setLastName("Doe");
        creator14.setPassword("iloveyou");
        creator14.setSchoolRole(SchoolRole.TEACHER);

        User editor14 = new User();
        editor14.setAddress(new Address());
        editor14.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor14.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor14.setCreator(new User());
        editor14.setDeleted(true);
        editor14.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor14.setEditor(new User());
        editor14.setEmail("jane.doe@example.org");
        editor14.setFirstName("Jane");
        editor14.setId(1L);
        editor14.setLastName("Doe");
        editor14.setPassword("iloveyou");
        editor14.setSchoolRole(SchoolRole.TEACHER);

        User creator15 = new User();
        creator15.setAddress(address12);
        creator15.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator15.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator15.setCreator(creator14);
        creator15.setDeleted(true);
        creator15.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator15.setEditor(editor14);
        creator15.setEmail("jane.doe@example.org");
        creator15.setFirstName("Jane");
        creator15.setId(1L);
        creator15.setLastName("Doe");
        creator15.setPassword("iloveyou");
        creator15.setSchoolRole(SchoolRole.TEACHER);

        Address address13 = new Address();
        address13.setCity("Oxford");
        address13.setCountryCode("GB");
        address13.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address13.setCreator(new User());
        address13.setDeleted(true);
        address13.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address13.setEditor(new User());
        address13.setHouseNumber("42");
        address13.setId(1L);
        address13.setStreet("Street");

        User creator16 = new User();
        creator16.setAddress(new Address());
        creator16.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator16.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator16.setCreator(new User());
        creator16.setDeleted(true);
        creator16.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator16.setEditor(new User());
        creator16.setEmail("jane.doe@example.org");
        creator16.setFirstName("Jane");
        creator16.setId(1L);
        creator16.setLastName("Doe");
        creator16.setPassword("iloveyou");
        creator16.setSchoolRole(SchoolRole.TEACHER);

        User editor15 = new User();
        editor15.setAddress(new Address());
        editor15.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor15.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor15.setCreator(new User());
        editor15.setDeleted(true);
        editor15.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor15.setEditor(new User());
        editor15.setEmail("jane.doe@example.org");
        editor15.setFirstName("Jane");
        editor15.setId(1L);
        editor15.setLastName("Doe");
        editor15.setPassword("iloveyou");
        editor15.setSchoolRole(SchoolRole.TEACHER);

        User editor16 = new User();
        editor16.setAddress(address13);
        editor16.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor16.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor16.setCreator(creator16);
        editor16.setDeleted(true);
        editor16.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor16.setEditor(editor15);
        editor16.setEmail("jane.doe@example.org");
        editor16.setFirstName("Jane");
        editor16.setId(1L);
        editor16.setLastName("Doe");
        editor16.setPassword("iloveyou");
        editor16.setSchoolRole(SchoolRole.TEACHER);

        User creator17 = new User();
        creator17.setAddress(address11);
        creator17.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator17.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator17.setCreator(creator15);
        creator17.setDeleted(true);
        creator17.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator17.setEditor(editor16);
        creator17.setEmail("jane.doe@example.org");
        creator17.setFirstName("Jane");
        creator17.setId(1L);
        creator17.setLastName("Doe");
        creator17.setPassword("iloveyou");
        creator17.setSchoolRole(SchoolRole.TEACHER);

        User creator18 = new User();
        creator18.setAddress(new Address());
        creator18.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator18.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator18.setCreator(new User());
        creator18.setDeleted(true);
        creator18.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator18.setEditor(new User());
        creator18.setEmail("jane.doe@example.org");
        creator18.setFirstName("Jane");
        creator18.setId(1L);
        creator18.setLastName("Doe");
        creator18.setPassword("iloveyou");
        creator18.setSchoolRole(SchoolRole.TEACHER);

        User editor17 = new User();
        editor17.setAddress(new Address());
        editor17.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor17.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor17.setCreator(new User());
        editor17.setDeleted(true);
        editor17.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor17.setEditor(new User());
        editor17.setEmail("jane.doe@example.org");
        editor17.setFirstName("Jane");
        editor17.setId(1L);
        editor17.setLastName("Doe");
        editor17.setPassword("iloveyou");
        editor17.setSchoolRole(SchoolRole.TEACHER);

        Address address14 = new Address();
        address14.setCity("Oxford");
        address14.setCountryCode("GB");
        address14.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address14.setCreator(creator18);
        address14.setDeleted(true);
        address14.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address14.setEditor(editor17);
        address14.setHouseNumber("42");
        address14.setId(1L);
        address14.setStreet("Street");

        Address address15 = new Address();
        address15.setCity("Oxford");
        address15.setCountryCode("GB");
        address15.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address15.setCreator(new User());
        address15.setDeleted(true);
        address15.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address15.setEditor(new User());
        address15.setHouseNumber("42");
        address15.setId(1L);
        address15.setStreet("Street");

        User creator19 = new User();
        creator19.setAddress(new Address());
        creator19.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator19.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator19.setCreator(new User());
        creator19.setDeleted(true);
        creator19.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator19.setEditor(new User());
        creator19.setEmail("jane.doe@example.org");
        creator19.setFirstName("Jane");
        creator19.setId(1L);
        creator19.setLastName("Doe");
        creator19.setPassword("iloveyou");
        creator19.setSchoolRole(SchoolRole.TEACHER);

        User editor18 = new User();
        editor18.setAddress(new Address());
        editor18.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor18.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor18.setCreator(new User());
        editor18.setDeleted(true);
        editor18.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor18.setEditor(new User());
        editor18.setEmail("jane.doe@example.org");
        editor18.setFirstName("Jane");
        editor18.setId(1L);
        editor18.setLastName("Doe");
        editor18.setPassword("iloveyou");
        editor18.setSchoolRole(SchoolRole.TEACHER);

        User creator20 = new User();
        creator20.setAddress(address15);
        creator20.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator20.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator20.setCreator(creator19);
        creator20.setDeleted(true);
        creator20.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator20.setEditor(editor18);
        creator20.setEmail("jane.doe@example.org");
        creator20.setFirstName("Jane");
        creator20.setId(1L);
        creator20.setLastName("Doe");
        creator20.setPassword("iloveyou");
        creator20.setSchoolRole(SchoolRole.TEACHER);

        Address address16 = new Address();
        address16.setCity("Oxford");
        address16.setCountryCode("GB");
        address16.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address16.setCreator(new User());
        address16.setDeleted(true);
        address16.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address16.setEditor(new User());
        address16.setHouseNumber("42");
        address16.setId(1L);
        address16.setStreet("Street");

        User creator21 = new User();
        creator21.setAddress(new Address());
        creator21.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator21.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator21.setCreator(new User());
        creator21.setDeleted(true);
        creator21.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator21.setEditor(new User());
        creator21.setEmail("jane.doe@example.org");
        creator21.setFirstName("Jane");
        creator21.setId(1L);
        creator21.setLastName("Doe");
        creator21.setPassword("iloveyou");
        creator21.setSchoolRole(SchoolRole.TEACHER);

        User editor19 = new User();
        editor19.setAddress(new Address());
        editor19.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor19.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor19.setCreator(new User());
        editor19.setDeleted(true);
        editor19.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor19.setEditor(new User());
        editor19.setEmail("jane.doe@example.org");
        editor19.setFirstName("Jane");
        editor19.setId(1L);
        editor19.setLastName("Doe");
        editor19.setPassword("iloveyou");
        editor19.setSchoolRole(SchoolRole.TEACHER);

        User editor20 = new User();
        editor20.setAddress(address16);
        editor20.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor20.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor20.setCreator(creator21);
        editor20.setDeleted(true);
        editor20.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor20.setEditor(editor19);
        editor20.setEmail("jane.doe@example.org");
        editor20.setFirstName("Jane");
        editor20.setId(1L);
        editor20.setLastName("Doe");
        editor20.setPassword("iloveyou");
        editor20.setSchoolRole(SchoolRole.TEACHER);

        User editor21 = new User();
        editor21.setAddress(address14);
        editor21.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor21.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor21.setCreator(creator20);
        editor21.setDeleted(true);
        editor21.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor21.setEditor(editor20);
        editor21.setEmail("jane.doe@example.org");
        editor21.setFirstName("Jane");
        editor21.setId(1L);
        editor21.setLastName("Doe");
        editor21.setPassword("iloveyou");
        editor21.setSchoolRole(SchoolRole.TEACHER);

        User creator22 = new User();
        creator22.setAddress(address10);
        creator22.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator22.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator22.setCreator(creator17);
        creator22.setDeleted(true);
        creator22.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator22.setEditor(editor21);
        creator22.setEmail("jane.doe@example.org");
        creator22.setFirstName("Jane");
        creator22.setId(1L);
        creator22.setLastName("Doe");
        creator22.setPassword("iloveyou");
        creator22.setSchoolRole(SchoolRole.TEACHER);

        Address address17 = new Address();
        address17.setCity("Oxford");
        address17.setCountryCode("GB");
        address17.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address17.setCreator(new User());
        address17.setDeleted(true);
        address17.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address17.setEditor(new User());
        address17.setHouseNumber("42");
        address17.setId(1L);
        address17.setStreet("Street");

        User creator23 = new User();
        creator23.setAddress(new Address());
        creator23.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator23.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator23.setCreator(new User());
        creator23.setDeleted(true);
        creator23.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator23.setEditor(new User());
        creator23.setEmail("jane.doe@example.org");
        creator23.setFirstName("Jane");
        creator23.setId(1L);
        creator23.setLastName("Doe");
        creator23.setPassword("iloveyou");
        creator23.setSchoolRole(SchoolRole.TEACHER);

        User editor22 = new User();
        editor22.setAddress(new Address());
        editor22.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor22.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor22.setCreator(new User());
        editor22.setDeleted(true);
        editor22.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor22.setEditor(new User());
        editor22.setEmail("jane.doe@example.org");
        editor22.setFirstName("Jane");
        editor22.setId(1L);
        editor22.setLastName("Doe");
        editor22.setPassword("iloveyou");
        editor22.setSchoolRole(SchoolRole.TEACHER);

        User creator24 = new User();
        creator24.setAddress(address17);
        creator24.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator24.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator24.setCreator(creator23);
        creator24.setDeleted(true);
        creator24.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator24.setEditor(editor22);
        creator24.setEmail("jane.doe@example.org");
        creator24.setFirstName("Jane");
        creator24.setId(1L);
        creator24.setLastName("Doe");
        creator24.setPassword("iloveyou");
        creator24.setSchoolRole(SchoolRole.TEACHER);

        Address address18 = new Address();
        address18.setCity("Oxford");
        address18.setCountryCode("GB");
        address18.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address18.setCreator(new User());
        address18.setDeleted(true);
        address18.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address18.setEditor(new User());
        address18.setHouseNumber("42");
        address18.setId(1L);
        address18.setStreet("Street");

        User creator25 = new User();
        creator25.setAddress(new Address());
        creator25.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator25.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator25.setCreator(new User());
        creator25.setDeleted(true);
        creator25.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator25.setEditor(new User());
        creator25.setEmail("jane.doe@example.org");
        creator25.setFirstName("Jane");
        creator25.setId(1L);
        creator25.setLastName("Doe");
        creator25.setPassword("iloveyou");
        creator25.setSchoolRole(SchoolRole.TEACHER);

        User editor23 = new User();
        editor23.setAddress(new Address());
        editor23.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor23.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor23.setCreator(new User());
        editor23.setDeleted(true);
        editor23.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor23.setEditor(new User());
        editor23.setEmail("jane.doe@example.org");
        editor23.setFirstName("Jane");
        editor23.setId(1L);
        editor23.setLastName("Doe");
        editor23.setPassword("iloveyou");
        editor23.setSchoolRole(SchoolRole.TEACHER);

        User editor24 = new User();
        editor24.setAddress(address18);
        editor24.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor24.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor24.setCreator(creator25);
        editor24.setDeleted(true);
        editor24.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor24.setEditor(editor23);
        editor24.setEmail("jane.doe@example.org");
        editor24.setFirstName("Jane");
        editor24.setId(1L);
        editor24.setLastName("Doe");
        editor24.setPassword("iloveyou");
        editor24.setSchoolRole(SchoolRole.TEACHER);

        Address address19 = new Address();
        address19.setCity("Oxford");
        address19.setCountryCode("GB");
        address19.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address19.setCreator(creator24);
        address19.setDeleted(true);
        address19.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address19.setEditor(editor24);
        address19.setHouseNumber("42");
        address19.setId(1L);
        address19.setStreet("Street");

        User creator26 = new User();
        creator26.setAddress(new Address());
        creator26.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator26.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator26.setCreator(new User());
        creator26.setDeleted(true);
        creator26.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator26.setEditor(new User());
        creator26.setEmail("jane.doe@example.org");
        creator26.setFirstName("Jane");
        creator26.setId(1L);
        creator26.setLastName("Doe");
        creator26.setPassword("iloveyou");
        creator26.setSchoolRole(SchoolRole.TEACHER);

        User editor25 = new User();
        editor25.setAddress(new Address());
        editor25.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor25.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor25.setCreator(new User());
        editor25.setDeleted(true);
        editor25.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor25.setEditor(new User());
        editor25.setEmail("jane.doe@example.org");
        editor25.setFirstName("Jane");
        editor25.setId(1L);
        editor25.setLastName("Doe");
        editor25.setPassword("iloveyou");
        editor25.setSchoolRole(SchoolRole.TEACHER);

        Address address20 = new Address();
        address20.setCity("Oxford");
        address20.setCountryCode("GB");
        address20.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address20.setCreator(creator26);
        address20.setDeleted(true);
        address20.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address20.setEditor(editor25);
        address20.setHouseNumber("42");
        address20.setId(1L);
        address20.setStreet("Street");

        Address address21 = new Address();
        address21.setCity("Oxford");
        address21.setCountryCode("GB");
        address21.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address21.setCreator(new User());
        address21.setDeleted(true);
        address21.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address21.setEditor(new User());
        address21.setHouseNumber("42");
        address21.setId(1L);
        address21.setStreet("Street");

        User creator27 = new User();
        creator27.setAddress(new Address());
        creator27.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator27.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator27.setCreator(new User());
        creator27.setDeleted(true);
        creator27.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator27.setEditor(new User());
        creator27.setEmail("jane.doe@example.org");
        creator27.setFirstName("Jane");
        creator27.setId(1L);
        creator27.setLastName("Doe");
        creator27.setPassword("iloveyou");
        creator27.setSchoolRole(SchoolRole.TEACHER);

        User editor26 = new User();
        editor26.setAddress(new Address());
        editor26.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor26.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor26.setCreator(new User());
        editor26.setDeleted(true);
        editor26.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor26.setEditor(new User());
        editor26.setEmail("jane.doe@example.org");
        editor26.setFirstName("Jane");
        editor26.setId(1L);
        editor26.setLastName("Doe");
        editor26.setPassword("iloveyou");
        editor26.setSchoolRole(SchoolRole.TEACHER);

        User creator28 = new User();
        creator28.setAddress(address21);
        creator28.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator28.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator28.setCreator(creator27);
        creator28.setDeleted(true);
        creator28.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator28.setEditor(editor26);
        creator28.setEmail("jane.doe@example.org");
        creator28.setFirstName("Jane");
        creator28.setId(1L);
        creator28.setLastName("Doe");
        creator28.setPassword("iloveyou");
        creator28.setSchoolRole(SchoolRole.TEACHER);

        Address address22 = new Address();
        address22.setCity("Oxford");
        address22.setCountryCode("GB");
        address22.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address22.setCreator(new User());
        address22.setDeleted(true);
        address22.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address22.setEditor(new User());
        address22.setHouseNumber("42");
        address22.setId(1L);
        address22.setStreet("Street");

        User creator29 = new User();
        creator29.setAddress(new Address());
        creator29.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator29.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator29.setCreator(new User());
        creator29.setDeleted(true);
        creator29.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator29.setEditor(new User());
        creator29.setEmail("jane.doe@example.org");
        creator29.setFirstName("Jane");
        creator29.setId(1L);
        creator29.setLastName("Doe");
        creator29.setPassword("iloveyou");
        creator29.setSchoolRole(SchoolRole.TEACHER);

        User editor27 = new User();
        editor27.setAddress(new Address());
        editor27.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor27.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor27.setCreator(new User());
        editor27.setDeleted(true);
        editor27.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor27.setEditor(new User());
        editor27.setEmail("jane.doe@example.org");
        editor27.setFirstName("Jane");
        editor27.setId(1L);
        editor27.setLastName("Doe");
        editor27.setPassword("iloveyou");
        editor27.setSchoolRole(SchoolRole.TEACHER);

        User editor28 = new User();
        editor28.setAddress(address22);
        editor28.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor28.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor28.setCreator(creator29);
        editor28.setDeleted(true);
        editor28.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor28.setEditor(editor27);
        editor28.setEmail("jane.doe@example.org");
        editor28.setFirstName("Jane");
        editor28.setId(1L);
        editor28.setLastName("Doe");
        editor28.setPassword("iloveyou");
        editor28.setSchoolRole(SchoolRole.TEACHER);

        User creator30 = new User();
        creator30.setAddress(address20);
        creator30.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator30.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator30.setCreator(creator28);
        creator30.setDeleted(true);
        creator30.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator30.setEditor(editor28);
        creator30.setEmail("jane.doe@example.org");
        creator30.setFirstName("Jane");
        creator30.setId(1L);
        creator30.setLastName("Doe");
        creator30.setPassword("iloveyou");
        creator30.setSchoolRole(SchoolRole.TEACHER);

        User creator31 = new User();
        creator31.setAddress(new Address());
        creator31.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator31.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator31.setCreator(new User());
        creator31.setDeleted(true);
        creator31.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator31.setEditor(new User());
        creator31.setEmail("jane.doe@example.org");
        creator31.setFirstName("Jane");
        creator31.setId(1L);
        creator31.setLastName("Doe");
        creator31.setPassword("iloveyou");
        creator31.setSchoolRole(SchoolRole.TEACHER);

        User editor29 = new User();
        editor29.setAddress(new Address());
        editor29.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor29.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor29.setCreator(new User());
        editor29.setDeleted(true);
        editor29.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor29.setEditor(new User());
        editor29.setEmail("jane.doe@example.org");
        editor29.setFirstName("Jane");
        editor29.setId(1L);
        editor29.setLastName("Doe");
        editor29.setPassword("iloveyou");
        editor29.setSchoolRole(SchoolRole.TEACHER);

        Address address23 = new Address();
        address23.setCity("Oxford");
        address23.setCountryCode("GB");
        address23.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address23.setCreator(creator31);
        address23.setDeleted(true);
        address23.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address23.setEditor(editor29);
        address23.setHouseNumber("42");
        address23.setId(1L);
        address23.setStreet("Street");

        Address address24 = new Address();
        address24.setCity("Oxford");
        address24.setCountryCode("GB");
        address24.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address24.setCreator(new User());
        address24.setDeleted(true);
        address24.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address24.setEditor(new User());
        address24.setHouseNumber("42");
        address24.setId(1L);
        address24.setStreet("Street");

        User creator32 = new User();
        creator32.setAddress(new Address());
        creator32.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator32.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator32.setCreator(new User());
        creator32.setDeleted(true);
        creator32.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator32.setEditor(new User());
        creator32.setEmail("jane.doe@example.org");
        creator32.setFirstName("Jane");
        creator32.setId(1L);
        creator32.setLastName("Doe");
        creator32.setPassword("iloveyou");
        creator32.setSchoolRole(SchoolRole.TEACHER);

        User editor30 = new User();
        editor30.setAddress(new Address());
        editor30.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor30.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor30.setCreator(new User());
        editor30.setDeleted(true);
        editor30.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor30.setEditor(new User());
        editor30.setEmail("jane.doe@example.org");
        editor30.setFirstName("Jane");
        editor30.setId(1L);
        editor30.setLastName("Doe");
        editor30.setPassword("iloveyou");
        editor30.setSchoolRole(SchoolRole.TEACHER);

        User creator33 = new User();
        creator33.setAddress(address24);
        creator33.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator33.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator33.setCreator(creator32);
        creator33.setDeleted(true);
        creator33.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator33.setEditor(editor30);
        creator33.setEmail("jane.doe@example.org");
        creator33.setFirstName("Jane");
        creator33.setId(1L);
        creator33.setLastName("Doe");
        creator33.setPassword("iloveyou");
        creator33.setSchoolRole(SchoolRole.TEACHER);

        Address address25 = new Address();
        address25.setCity("Oxford");
        address25.setCountryCode("GB");
        address25.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address25.setCreator(new User());
        address25.setDeleted(true);
        address25.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        address25.setEditor(new User());
        address25.setHouseNumber("42");
        address25.setId(1L);
        address25.setStreet("Street");

        User creator34 = new User();
        creator34.setAddress(new Address());
        creator34.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator34.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator34.setCreator(new User());
        creator34.setDeleted(true);
        creator34.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        creator34.setEditor(new User());
        creator34.setEmail("jane.doe@example.org");
        creator34.setFirstName("Jane");
        creator34.setId(1L);
        creator34.setLastName("Doe");
        creator34.setPassword("iloveyou");
        creator34.setSchoolRole(SchoolRole.TEACHER);

        User editor31 = new User();
        editor31.setAddress(new Address());
        editor31.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor31.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor31.setCreator(new User());
        editor31.setDeleted(true);
        editor31.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor31.setEditor(new User());
        editor31.setEmail("jane.doe@example.org");
        editor31.setFirstName("Jane");
        editor31.setId(1L);
        editor31.setLastName("Doe");
        editor31.setPassword("iloveyou");
        editor31.setSchoolRole(SchoolRole.TEACHER);

        User editor32 = new User();
        editor32.setAddress(address25);
        editor32.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor32.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor32.setCreator(creator34);
        editor32.setDeleted(true);
        editor32.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor32.setEditor(editor31);
        editor32.setEmail("jane.doe@example.org");
        editor32.setFirstName("Jane");
        editor32.setId(1L);
        editor32.setLastName("Doe");
        editor32.setPassword("iloveyou");
        editor32.setSchoolRole(SchoolRole.TEACHER);

        User editor33 = new User();
        editor33.setAddress(address23);
        editor33.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor33.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor33.setCreator(creator33);
        editor33.setDeleted(true);
        editor33.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor33.setEditor(editor32);
        editor33.setEmail("jane.doe@example.org");
        editor33.setFirstName("Jane");
        editor33.setId(1L);
        editor33.setLastName("Doe");
        editor33.setPassword("iloveyou");
        editor33.setSchoolRole(SchoolRole.TEACHER);

        User editor34 = new User();
        editor34.setAddress(address19);
        editor34.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor34.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor34.setCreator(creator30);
        editor34.setDeleted(true);
        editor34.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        editor34.setEditor(editor33);
        editor34.setEmail("jane.doe@example.org");
        editor34.setFirstName("Jane");
        editor34.setId(1L);
        editor34.setLastName("Doe");
        editor34.setPassword("iloveyou");
        editor34.setSchoolRole(SchoolRole.TEACHER);

        User user = new User();
        user.setAddress(address7);
        user.setBirthDate(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        user.setCreated(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        user.setCreator(creator22);
        user.setDeleted(true);
        user.setEdited(Date.from(LocalDate.of(1970, 1, 1).atStartOfDay().atZone(ZoneOffset.UTC).toInstant()));
        user.setEditor(editor34);
        user.setEmail("jane.doe@example.org");
        user.setFirstName("Jane");
        user.setId(1L);
        user.setLastName("Doe");
        user.setPassword("iloveyou");
        user.setSchoolRole(SchoolRole.TEACHER);
        when(userRepository.findUserByEmail(Mockito.<String>any())).thenReturn(user);

        // Act
        User actualLoadUserByUsernameResult = userService.loadUserByUsername("jane.doe@example.org");

        // Assert
        verify(userRepository, atLeast(1)).findUserByEmail(Mockito.<String>any());
        assertSame(user, actualLoadUserByUsernameResult);
    }
}
